- package.json
Make sure `license` value in package.json agrees w/ LICENSE file in repository
> fix package.json w/ correct license value

- src/merkle/digest.test.ts
- src/merkle/digest.ts
- src/merkle/index.ts
- src/merkle/verify.test.ts
- src/merkle/verify.ts
Adds a `verifyInclusion` function which can validate the Merkle tree inclusion proof information embedded in a Rekor bundle.
Probably want to integrate this into the `Verifier` class so that the inclusion proof can be checked anytime we retrieve a bundle from Rekor.
Largely inspired by https://github.com/transparency-dev/merkle/blob/main/proof/verify.go#L46
> support for verifying merkle inclusion proofs

- .github/workflows/build-sign-verify.yml
- use git hashes instead of tags for actions
Across sigstore org we use the git hash instead of the git tags for the actions to pin in a specific git commit
> use git hashes instead of tags for actions

- .github/workflows/build-sign-verify.yml
- README.md
- src/cli/index.ts
- src/dsse.test.ts
- src/dsse.ts
- src/sigstore.test.ts
- src/sigstore.ts
- src/verify.test.ts
- src/verify.ts
Closes #36 
**Summary**
Updates the `sigstore.verify` function to make the signing certificate a required parameter. Previously, we were searching the Rekor log to retrieve the signing certificate, but this is not the recommended approach.
There is a lot more to be done as part of the verify workflow -- currently, there is verification against the Rekor log at all (either offline or online). We'll come back and address this in a separate PR.
**Release Notes**
* `sigstore.verify` now requires the signing certificate be passed as a parameter
* `dsse.verify` now requires the signing certificate be passed as a parameter
* `Verifier.verify` no longer searches Rekor to find the signing certificate
* The `sign` CLI command now saves the Fulcio-issued signing certificate so it can be saved for …
> make certificate mandatory for verification

- src/client/rekor.test.ts
- src/client/rekor.ts
- src/sign.ts
- src/verify.ts
Updates the `Rekor` client to support "intoto" entry uploads. Previously, the only entry kind that the client knew how to deal with was "hashrekord". The changes here lay the groundwork for supporting all of the various entry kinds in the future but is primarily focused on the "hashrekord" and "intoto" kinds for now.
* Updates the `Rekor.createEntry` function to support creating entries of any kind.
* Adds a new `Rekor.createIntotoEntry` convenience function.
* Adds a new `Rekor.createHashedRekordEntry` convenience function.
* Renames the `Rekor.searchLog` function to `Rekor.searchIndex` to better reflect which API is being wrapped.
> add intoto support to rekor client

- src/cli/index.ts
- src/client/rekor.ts
- src/sigstore.ts
Currently, the README.md file refers to output from the sign command:
```console
Created entry at index 2698234, available at
https://rekor.sigstore.dev/api/v1/log/entries/43553c769...
```
It looks like this output was removed in Commit bd596c0eccd6104589e596c34936a6c46a2e30ae ("proper signing/verification for attestations").
This commit suggest re-adding this output as I was not sure how to get
to this information otherwise. I'm very new to this code base but
hopefully someone can provide some feedback if there are other ways,
or if the README.md should be updated instead.
N/A
N/A
Signed-off-by: Daniel Bevenius <daniel.bevenius@gmail.com>
> Re-add logging of Rekor entry index and url

- src/cli/index.ts
This commit adds very basic command line `help` and `version` command line options.
The motivation for this that I tried running sigstore --help out of habit but that returned `Unknown command`. Perhaps others will do this same and this commit could be a start of adding more options/details.
This can be tested using the following commands:
```console
$ npm run build
$ ./bin/sigstore.js --help
sigstore <command> <artifact>
Usage:
sigstore sign         sign an artifact
sigstore sign-dsse    sign an artifact using dsse (Dead Simple Signing Envelope)
sigstore verify       verify an artifact
```
Perhaps this can be expanded upon and cleaned up by using a module like yargs, but I was not sure if adding a dependency would be considered ok, and if there might be preferences of which module to use …
> Add basic help and version command line option

- src/sign.test.ts
- src/sign.ts
- src/types/bundle/index.test.ts
- src/types/bundle/index.ts
- src/types/rekor/index.test.ts
- src/types/rekor/index.ts
- src/types/signature.ts
Updates the `Signer` class to support a user-provided `SignerFunc` which is responsible for generating and returning an artifact signature. If no `SignerFunc` is provided, it defaults to using the standard ephemeral keypair w/ Fulcio certificate signing scheme.
Allowing for a a custom signing function allows us to support scenarios where a user may want to use something like a KMS key to generate a signature which still utilizing the rest of the Sigstore workflow (upload to Rekor, bundle creation, etc).
Lays the foundation for user-supplied signing functions. Note that this isn't yet exposed as part of the package's public interface. Will add that in a subsequent commit.
> Support custom signer callback

- src/cli/index.ts
- src/client/rekor.ts
- src/sign.test.ts
- src/sign.ts
- src/sigstore.test.ts
- src/sigstore.ts
- src/tlog/index.test.ts
- src/tlog/index.ts
- src/types/bundle/index.ts
- src/types/signature.test.ts
- src/types/signature.ts
- src/verify.test.ts
- src/verify.ts
Exposes a new public `addEnvelopeToTransparencyLog` function which allows a user with an existing, signed DSSE envelope to post that envelope to Rekor and receive a Sigstore bundle in return.
```typescript
function addEnvelopeToTransparencyLog(envelope: Envelope, key: string): Promise<Bundle> { }
```
As part of exposing this function, I introduced a new `TLog` class which sits atop the `Rekor` class. Whereas `Rekor` provided direct access to the Rekor REST API, the new `TLog` class encapsulates the logic necessary to marshal data to/from the Rekor request/response formats. Ultimately, I'd like to do something similar on top of the `Fulcio` client, but I'll save that for another refactor.
* Adds new `addEnvelopeToTransparencyLog` to public …
> Expose new addEnvelopToTransparencyLog function

- src/sigstore.ts
- src/types/bundle/index.ts
- src/types/bundle/serialized.ts
Modifies the interface of `createRekorEntry` to take a "serialized dsse envelope" which is a JSON representation and de-serialize it internally.
> Accept serialized envelope in createRekorEntry

- src/sigstore-utils.test.ts
- src/sigstore-utils.ts
- src/sigstore.test.ts
- src/sigstore.ts
- src/types/bundle/index.ts
Creates a dsse envelope using a custom signer. The output of this function can be passed to `createRekorEntry` along with a public key in order to separate signing and the Rekor upload.
> Add createDSSEEnvelope method

- src/tlog/keys.ts
When install `sigstore` as a library the library is executed from the projects root, so reading `'store/rekor.pub'` is not found and errors: `ENOENT: no such file or directory, open 'store/rekor.pub'`
> Fix absolute path to rekor public key

- src/sigstore.test.ts
- src/tlog/verify.ts
- src/util/index.ts
- src/util/x509.test.ts
- src/util/x509.ts
- src/verify.ts
Updates the verification logic with a check which will compare the `integratedTime` of all tlog entries against the validity period of the signing certificate. 
If the `integratedTime` occurs before the certificate's "Not Before" time or after the certificate's "Not After" time the bundle will be considered invalid.
> verify tlog integrated time against signing cert

- src/tlog/format.test.ts
- src/tlog/format.ts
- src/tlog/verify.test.ts
Updates the logic to properly calculate the digest of a DSSE envelope when creating an intoto/0.0.2 style entry in Rekor.
> update rekor intoto/0.0.2 entry hash calculation

- src/sigstore.ts
- src/verify.test.ts
- src/verify.ts
Updates the `verify` function to accept an optional `findKey` callback which can be used to retrieve the public key for verifying signatures which are not using a signing certificate (cases where verification material in the bundle specifies a public key hint instead of a certificate chain).
In a subsequent PR, the same key returned by `findKey` will also be passed-down to the tlog verification logic and used to re-create the Rekor entry for SET verification.
* Updates the signature for the `verify` function to accept an optional `findKey` callback which will be invoked to retrieve the public key in scenarios where the signature was generated w/ a static keypair.
> support for public key retrieval callback

- src/tlog/verify.test.ts
- src/tlog/verify.ts
- src/verify.ts
Continues the work in https://github.com/sigstore/sigstore-js/pull/152 to integrate a `getPublicKey` callback option which can be used for verification when artifacts are signed w/ a static keypair. This change passes the retrieved key down into the SET verification function to ensure that the correct key value is used when re-creating the Rekor entry.
> refactor key handling for rekor SET verification

- src/__tests__/client/error.test.ts
- src/client/error.ts
Updates the `HTTPError` class to include a `statusCode` property which is populated with the HTTP status code of the response in error.
> add statusCode property to HTTPError

- src/__tests__/tlog/verify.test.ts
- src/tlog/types/index.ts
- src/tlog/verify.ts
- src/verify.ts
Internal refactoring of the transparency log verification logic to improve efficiency.
Previously, there were three separate transparency log verification steps which were exposed as separate functions:
* Verification of the canonicalized transparency log body
* Verification of the transparency log SET
* Verification of the transparency log integrated time.
With this refactor, all three of these checks are rolled into a single `verifyTLogEntries` function which performs these operations across all transparency log entries in the bundle.
> refactor tlog verification

- README.md
Adds some notes to the README explaining how to publish a new package release. I hope to automate more of this in the future, but this at least gets us to a place where packages are built/published from GitHub Actions.
> Add steps for package publishing to readme

- src/__tests__/util/stream.test.ts
- src/__tests__/x509/asn1/length.test.ts
- src/__tests__/x509/asn1/obj.test.ts
- src/__tests__/x509/asn1/parse.test.ts
- src/__tests__/x509/asn1/tag.test.ts
- src/util/stream.ts
- src/x509/asn1/dump.ts
- src/x509/asn1/error.ts
- src/x509/asn1/length.ts
- src/x509/asn1/obj.ts
- src/x509/asn1/parse.ts
- src/x509/asn1/tag.ts
Adds support for basic parsing of DER-encoded ASN.1 objects. This lays the groundwork for adding full x509 certificate support so that we can do verification of the Fulcio certificate chain.
This implementation does not support the complete set of ANS.1 datatypes or encoding options. For now, it is focused exclusively on the ASN.1 types commonly used in x509 certificates using DER encoding:
* `BOOLEAN`
* `INTEGER`
* `BIT STRING`
* `OCTET STRING`
* `OBJECT IDENTIFER`
* `SEQUENCE`
* `SET`  
* `PrintableString`
* `UTCTime`
Following is the structure resulting from parsing a Fulcio-issued x509 signing certificate:
```
SEQUENCE (3 elem) 
SEQUENCE (8 elem) 
[0] (1 elem) 
INTEGER (1 byte) 2
INTEGER (20 byte) 651968271402900508168874304870743208745138152437
SEQUENCE (1 elem) 
OBJECT IDENTIFIER …
```
> ASN.1 Parsing

- package-lock.json
- package.json
- tsconfig.json
Supported node versions is currently set to `^14.17.0 || ^16.13.0 || >=18.0.0`. The diff between these two `tsconfig.json` files is:
```diff
diff --git a/bases/node12.json b/bases/node14.json
index eeaf944..d1d7551 100644
--- a/bases/node12.json
+++ b/bases/node14.json
@@ -1,11 +1,11 @@
{
"$schema": "https://json.schemastore.org/tsconfig",
-  "display": "Node 12",
+  "display": "Node 14",
"compilerOptions": {
-    "lib": ["es2019", "es2020.promise", "es2020.bigint", "es2020.string"],
+    "lib": ["es2020"],
"module": "commonjs",
-    "target": "es2019",
+    "target": "es2020",
"strict": true,
"esModuleInterop": true,
```
> chore: bump `tsconfig` from `node12` to `node14`

- .github/workflows/publish.yml
Simplifies the set-up for publishing the package w/ provenance using the pre-release version of the npm CLI
> simplify workflow for publishing w/ provenance

- src/__tests__/x509/cert.test.ts
- src/x509/cert.ts
Add's a `verify` method to the `x509Certificate` class which can be used to verify the certificate's signature against the public key of its issuer.
> add verify method to x509Certificate class

- src/__tests__/x509/cert.test.ts
- src/x509/cert.ts
- src/x509/ext.ts
Updates the `x509Certificate` class with support for the "authorityKeyIdentifier" extension.
> authorityKeyID extension support for x509 certs

- .github/workflows/auto-merge.yml
Simplify Dependabot workflow by enabling auto-merge for Dependabot-issued PRs. This will cause the PRs to be merged automatically once the tests have passed and they have been approved.
> enable auto-merge for dependabot PRs

- src/__tests__/x509/cert.test.ts
- src/x509/cert.ts
- src/x509/ext.ts
Updates the `x509Certificate` class with support for the "subjectKeyIdentifier" extension.
> subjectKeyID extension support for x509 certs

- .gitignore
- hack/ca/Makefile
- hack/ca/README.md
- hack/ca/ca.conf
Adds a `Makefile` to the "hack" directory that can be used to generate different x509 certificates for testing things like ASN.1 parsing and certificate chain verification. The generated certificates are set-up specifically to mimic the root/intermediate/leaf certificates used by Fulcio.
Example Root Cert:
```
Certificate:
Data:
Version: 3 (0x2)
Serial Number:
41:21:4b:16:2f:50:72:3e:da:02:7f:c9:21:50:81:c5:e0:24:68:47
Signature Algorithm: ecdsa-with-SHA384
Issuer: O = foobar.dev, CN = foobar
Validity
Not Before: Jan  1 00:00:00 1990 GMT
Not After : Jan  1 00:00:00 2040 GMT
Subject: O = foobar.dev, CN = foobar
Subject Public Key Info:
Public Key Algorithm: id-ecPublicKey
Public-Key: (384 bit)
pub:
04:a8:e5:d5:7a:87:5b:b2:40:a0:9d:ec:d7:47:8c:
14:46:34:af:66:30:69:b3:a5:9c:aa:81:8f:fb:70: …
```
> Set-up cert CA for generating test data

- src/__tests__/tlog/index.test.ts
- src/client/error.ts
- src/sigstore-utils.ts
- src/tlog/index.ts
Adds a `fetchOnConflict` option to `tlog.createDSSEEntry` which allows it to retrieve/return an existing Rekor entry in the event that the entry being creating matches an existing record. The default behavior is still to throw an error in the event of a conflict (HTTP status code 409), but the `fetchOnConflict` flag  can be enabled to override this behavior.
> Fetch existing Rekor entry on create conflict

- src/__tests__/util/crypto.test.ts
- src/util/crypto.ts
Adds a `createPublicKey` function to the crypto utility module which can be used to parse either PEM- or DER-encoded keys and turn them into `KeyLike` objects which can be passed to the sign and verify functions.
Also updates the `verifyBlob` function signature to accept an optional algorithm param which can be used to identify the hash algorithm which should be used when verifying the signature of an artifact.
> add createPublicKey to crypto utility module

- src/__tests__/x509/sct.test.ts
- src/types/sigstore/index.ts
- src/x509/sct.ts
Adds support for parsing and verifying an encoded Signed Certificate Timestamp (SCT)
> signed certificate timestamp parsing

- src/__tests__/x509/ext.test.ts
- src/x509/ext.ts
Updates the `x509SCTExtension` class to add support for parsing the list of signed-certificate timestamps from the certificate extension.
> parse SCT list from cert extension

- src/__tests__/x509/cert.test.ts
- src/x509/cert.ts
Adds a `verifySCTs` function to the `x509Certificate` class which will verify each of the signed-certificate timestamps in the SCT extension against the certificate's issuer and the transparency log public key.
> verification of cert-embedded SCTs

- src/__tests__/x509/verify.test.ts
- src/x509/verify.ts
Updates the `verifyCertificateChain` function to return the verified chain of certificates (as an ordered array of `x509Certificate` objects). By returning the specific list of verified certificates we can use this as input to the SCT verifier to ensure that we are checking the SCTs in the signing certificate against the proper issuer.
> update cert verifier to return trusted chain

- src/__tests__/x509/cert.test.ts
- src/x509/cert.ts
Updates the return type of the `verifySCTs` method on the certificate class to return an array of results instead of a rolled-up boolean. As part of the bundle verification we need to be able to count the number of SCTs in the signing certificate which were successfully verified.
> update return type of verifySCTs

- src/__tests__/types/index.test.ts
- src/types/index.ts
- src/types/sigstore/index.ts
Adds a couple of helper functions to convert from the legacy (current) bundle format to the v1 (proposed) format. These will be removed once we have migrated everything to the v1 format, but I don't want to write anymore code against the old format, so I'll use this shim as a temporary way to stitch together code relying on different versions of the bundle.
> bundle conversion helper functions

- store/trusted_root.json
Adds the trusted root with all the keys/certificates necessary to verify the bundle. Once we have TUF integration we'll be able to update the trusted root with the latest trusted verification material. I'm using the same `TrustedRoot` format defined in the [sigstore/protobuf repo](https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_trustroot.proto#L70-L86).
> add trusted root

- src/__tests__/ca/format.test.ts
- src/__tests__/ca/index.test.ts
- src/__tests__/sign.test.ts
- src/__tests__/sigstore.test.ts
- src/ca/format.ts
- src/ca/index.ts
- src/client/fulcio.ts
- src/sign.ts
- src/sigstore.ts
Introduces a new `CAClient` which sits between the `Signer` and the `Fulcio` client. This helps to encapsulate some of the details around formatting the Fulcio certificate request (which will come in handy when we switch to the v2 API at some point) and also mirrors the way that we have fronted the `Rekor` API client w/ a `TLog` class.
This will also give us a nice place to add the Fulcio-specific certificate verification logic.
> introduce new CA client class

- src/__tests__/ca/verify.test.ts
- src/ca/verify.ts
Adds a `verifySigningCertificate` function which accepts a Sigstore bundle and a trusted root and will perform all of the necessary verification steps on the certificate chain contained in the bundle (certificated chain verification, and verification of any SCTs in the signing certificate).
> verification of bundle certificates

- src/__tests__/ca/verify.test.ts
- src/__tests__/types/sigstore/index.test.ts
- src/ca/verify.ts
- src/types/sigstore/index.ts
Establishes some "narrowed" versions of the types generated from the Sigstore protobufs. Specifically:
* `BundleWithCertificateChain` - a version of the Sigstore `Bundle` which is known to have a Fulcio certificate chain as part of the verification material.
* `CAArtifactVerificationOptions` a version of the `ArtifactVerificationOptions` which is known to contain the `ctlogOptions` and `signers` data necessary to verify a bundle containing a Fulcio certificate chain.
Using these narrowed types (and associated type guards) limits the number of places where we need to check for the presence of certain optional values as we pass these objects through the various layers of the system.
I expect to add more types like this as I build out the …
> narrow some of the sigstore generated types

- src/__tests__/ca/verify/index.test.ts
- src/ca/verify/chain.ts
- src/ca/verify/index.ts
- src/ca/verify/sct.ts
This is just a refactor of the existing certificate verification code, splitting it into multiple files. The original "src/ca/verify.ts" was getting pretty long (and I'm about to add a bunch more verification logic in support of signer identity verification) so I'm splitting it across multiple files to make it a bit more maintainable.
May come back and do a similar decomposition of the unit tests at some point, but leaving these as-is for now.
> split CA verification code into multiple files

- hack/ca/Makefile
- src/__tests__/__fixtures__/certs.ts
- src/__tests__/ca/verify/index.test.ts
- src/__tests__/ca/verify/signer.test.ts
- src/ca/verify/index.ts
- src/ca/verify/signer.ts
- src/x509/cert.ts
- src/x509/ext.ts
Adds a new `verifySignerIdentity` function which will verify the Fulcio-issued signing certificate against the signer identity contained in the `ArtifactVerificationOptions`
```
verifySignerIdentity
when there is a matching identity
when only one identity is specified
✓ returns without error
when the matching identity has an empty OID list
✓ returns without error
when the identity list contains a non-matching identity
✓ returns without error
when there is NO matching identity
when the issuer does not match
✓ throws an error
when the certificate does NOT have a SAN extension
✓ throws an error
when the required SAN is NOT specified
✓ throws an error
when the required SAN identity is NOT specified
✓ throws an error 
when the required SAN type is NOT specified
✓ throws an error
when the …
```
> signer identity verification

- src/__tests__/ca/verify/index.test.ts
- src/ca/verify/index.ts
- src/types/sigstore/index.ts
Loosens the requirement that the Fulcio-issued signing certificate must ALWAYS be verified against a list of approved signers. There are use cases where we may not have this information and still want to perform basic verification of the certificate.
> allow for optional signer identity verification

- src/__tests__/tlog/verify/set.test.ts
- src/tlog/verify/set.ts
- src/types/sigstore/index.ts
- src/types/utility.ts
Re-implementation of the `verifyTLogSET` function to account for the fact that we need to be able check the SET against multiple trusted TLog instances -- returning `true` as long as we get verification against one of them.
Note that I'm adding this alongside the existing implementation until I finish refactoring all of the TLog verification functions. At that time, I'll remove the old code and wire-in the new implementations.
```
verifyTLogSET
when there is a matching TLogInstance
when the SET can be verified
✓ returns true 
when the SET can NOT be verified
✓ returns false
when the matching TLogInstance has no public key
✓ returns false
when the matching TLogInstance has an empty public key
✓ returns false
when the public key for the …
```
> revisit implementation for verifyTLogSET

- src/__tests__/tlog/verify/index.test.ts
- src/__tests__/types/sigstore/index.test.ts
- src/tlog/verify/index.ts
- src/types/sigstore/index.ts
Adds some more "narrowed" versions of the Sigstore-generated types to reduce unnecessary `undefined`-checking:
* `BundleWithVerificationMaterial` - Sigstore bundle where the `verificationMaterial` field is guaranteed to be defined
* `RequiredArtifactVerificationOptions` - Subtype of `ArtifactVerificationOptions` with the `ctlogOptions` and `tlogOptions` fields guaranteed to be defined.
Also updates the `CAArtifactVerificationOptions` type to make the `signers` field optional.
> add narrowed versions of sigstore generated types

- src/__tests__/__fixtures__/bundles/signature.ts
Updates the set of Sigstore bunlde test fixtures to allow for testing different failure modes for invalid bundles.
> add some new test bundle fixtures

- src/__tests__/__fixtures__/bundles/signature.ts
- src/__tests__/verify.test.ts
- src/sigstore.ts
- src/types/sigstore/index.ts
- src/verify.ts
Updates the interface of the `Verifier` to use the new `ValidBundle` type (which narrows the standard `Bundle` to a type for which we know all of the required fields have been populated). This allows us to remove a bunch of if-defined checks we have scattered across the code (and the associated unit tests).
> integrate ValidBundle type

- src/__tests__/sigstore.test.ts
- src/sigstore.ts
Update the `VerifyOptions` w/ a new `certificateOIDs` field which allows the caller to supply a list of OID/value pairs which will be used when verifying the signer identity in the Fulcio-issued signing certificate.
> signing cert extension verification by OID

- src/__tests__/ca/index.test.ts
- src/__tests__/sign.test.ts
- src/__tests__/sigstore.test.ts
- src/__tests__/tlog/index.test.ts
- src/__tests__/tuf/trustroot.test.ts
- src/__tests__/types/sigstore/validate.test.ts
- src/ca/index.ts
- src/ca/verify/signer.ts
- src/error.ts
- src/tlog/index.ts
- src/tlog/verify/body.ts
- src/tuf/trustroot.ts
- src/types/sigstore/validate.ts
- src/x509/verify.ts
Standardizes a bunch of the error handling code and streamlines the set of raised errors to the following:
* `ValidationError` - The supplied bundle is malformed in some way (missing and/or invalid fields)
* `VerificationError` - Unable to verify the content of the bundle (signature mismatch, invalid SET, untrusted certificate chain, etc)
* `PolicyError` - The bundle is otherwise valid, but was signed by an untrusted identity.
* `InternalError` - Any unexpected error during signing/verification (unable to connect to TUF root, error trying to request signing certificate from Fulcio, etc)
> streamline error handling

- src/__tests__/sigstore.test.ts
- src/cli/index.ts
- src/sigstore-utils.ts
- src/sigstore.ts
Refactoring the public interface in preparation for the 1.0.0 release (per https://github.com/sigstore/sigstore-js/issues/287):
* `signAttestation` function renamed to `attest`
* `rekorBaseURL` option renamed to `rekorURL`
* `fulcioBaseURL` option renamed to `fulcioURL`
* `tufRootPath` option removed
* `data` param in `verify` function renamed to `payload` (to match param name in `sign` function)
* Swapped the order of the `payload` and `options` params in the `verify` function
> public interface clean-up

- .github/workflows/smoke-test.yml
Fix bug in smoke test workflow introduced with recent refactor of the CLI
> update smoke-test workflow with new CLI command

- .github/workflows/publish.yml
Updates the publish workflow to use the latest version of the npm CLI (w/ the `--provenance` flag).
> Use latest npm CLI in publish workflow

- .github/workflows/scorecard-debug.yml
Workflow for debugging errors with OSSF Scorecard. Will delete this once we figure out the issue.
Per: https://github.com/ossf/scorecard-action/issues/1076#issuecomment-1405519720
> scorecard debugging

- tsconfig.json
Remove duplicate tsconfig options.
The `strict` and `forceConsistentCasingInFileNames` options we recently added to the "tsconfig.json" are already set as part of the "@tsconfig/node14/tsconfig.json" file we're inheriting from.
https://github.com/tsconfig/bases/blob/d699759e29cfd5f6ab0fab9f3365c7767fca9787/bases/node14.json#L1-L16
> remove duplicate tsconfig options

- .changeset/tasty-lions-melt.md
- README.md
- src/__tests__/identity/ci.test.ts
- src/identity/ci.ts
This adds support for reading OIDC tokens from the SIGSTORE_ID_TOKEN environment variable. This mimics the behavior of https://github.com/sigstore/cosign/commit/9b482a5e37d7717a4729544268dd6f928f4af4f6.
The main motivation for supporting this is to enable support for GitLab CI authentication
(https://gitlab.com/gitlab-org/gitlab/-/issues/404793), i.e. for cosign:
```sh
build:
stage: build
id_tokens:
SIGSTORE_ID_TOKEN:
aud: sigstore
script:
- cosign sign ...
```
Added new token provider for looking up OIDC tokens in the `SIGSTORE_ID_TOKEN` environment variable.
✅
> identity: Add support for getting OIDC token from env var.

- .changeset/fuzzy-parents-own.md
- src/tuf/index.ts
This swaps over the default URL for the sigstore TUF root to use a CDN-backed endpoint instead of hitting GCS directly. There should be no different in content delivered, but static files within the root will be now be returned from the cache.
> use CDN instead of GCS endpoint for TUF root

- .changeset/gentle-panthers-pump.md
- src/cli/index.ts
Print the rekor search entry when running the `sigstore attest` command. We already did this for `sigstore sign` so refactored slightly to share.
> sigstore attest: print rekor entry

- .changeset/ninety-walls-behave.md
- README.md
- src/__tests__/__fixtures__/bundles/dsse.ts
- src/__tests__/sign.test.ts
- src/__tests__/verify.test.ts
- src/config.ts
- src/sign.ts
- src/sigstore.ts
- src/verify.ts
Introduces a new `tlogUpload` option to the `sign` and `attest` functions which can be used to control whether the generated signature is uploaded to the transparency log. Defaults to `true`.
> add tlogUpload option

- .changeset/tender-crabs-obey.md
- packages/cli/src/commands/attest.ts
Bugfix in CLI to support `--tlog-upload` flag
> fix tlog-upload flag in cli

- .changeset/friendly-kangaroos-raise.md
- packages/cli/README.md
- packages/cli/src/commands/attest.ts
Updates the CLI to use it's embedded OAuth identity provider instead of the one bundled in the core library. This is the first step toward deprecating the older OAuth implementation.
> use new oauth identity provider in cli

- .changeset/wicked-keys-smash.md
Promoting `@sigstore/tuf` to 1.0.0 for inclusion in the next release of the `sigstore` package.
> promote @sigstore/tuf to 1.0.0

- .changeset/fluffy-squids-report.md
- package-lock.json
- packages/mock/package.json
Removes an extraneous dependency from the `mock` package.
> remove extra dependency in mock pkg

- .changeset/shaggy-rocks-fly.md
- packages/sign/src/__tests__/error.test.ts
- packages/sign/src/__tests__/external/error.test.ts
- packages/sign/src/__tests__/external/fulcio.test.ts
- packages/sign/src/__tests__/external/rekor.test.ts
- packages/sign/src/__tests__/external/tsa.test.ts
- packages/sign/src/error.ts
- packages/sign/src/external/error.ts
- packages/sign/src/external/fulcio.ts
- packages/sign/src/external/rekor.ts
- packages/sign/src/external/tsa.ts
- packages/sign/src/signer/fulcio/ca.ts
- packages/sign/src/witness/tlog/client.ts
- packages/sign/src/witness/tsa/client.ts
Resovles #561 
Improved messaging when throwing errors originating from Sigstore services.  Previously, when responding to an error from Fulcio, the consumer would see a generic errror message like this:
```
InternalError: error creating signing certificate
```
This explains that there was some sort of issue with the creation of the certificate, but doesn't relay the specific issue reported by Fulcio.
With this change, the consumer will see the following:
```
InternalError: error creating signing certificate - (400) There was an error processing the identity token
```
Now they have the HTTP status code and the specific Fulcio-reported error message available.
> surface error msgs from sigstore services

- .changeset/slow-weeks-shop.md
- packages/mock/src/rekor/tlog.ts
Fixes a bug in the `mock` library which was generating an invalid merkle tree inclusion proof.
When calculating the leaf hash for the merkle tree inclusion proof, the base-64 encoding of the tlog entry was being used instead of the raw bytes.
> fix bug in mocked inclusion proof calculation

- .changeset/cyan-impalas-look.md
- package-lock.json
- packages/sign/src/__tests__/witness/tlog/index.test.ts
- packages/sign/src/witness/tlog/index.ts
Exposes an option on the `RekorWitness` class which allows the caller to choose between "intoto" and "dsse" entry types when creating a new TLog entry. Will continue to default to "intoto" if no value is specified.
> expose rekor option to choose 'intoto' or 'dsse'

- .github/workflows/dependabot-changesets.yml
Temporarily disabling the dependabot changeset action to troubleshoot some issues related to CI checks on dependabot PRs.
> disable dependabot changesets pr trigger

- .changeset/selfish-ants-exercise.md
- packages/verify/src/__tests__/policty.test.ts
- packages/verify/src/__tests__/verifier.test.ts
- packages/verify/src/policy.ts
- packages/verify/src/shared.types.ts
- packages/verify/src/verifier.ts
Updates the verifier with support for verifying the identity contained in the signing certificate. Given that not all Sigstore bundles contain a signing certificate, the `policy` argument containing the expected identity is marked as optional.
> add identity/issuer policy support to verifier

- .changeset/nine-donuts-marry.md
- .changeset/tricky-owls-relax.md
- packages/mock-server/src/index.ts
- packages/mock/src/timestamp/tsa.test.ts
- packages/mock/src/timestamp/tsa.ts
- packages/mock/src/util/ess-cert-id.test.ts
- packages/mock/src/util/ess-cert-id.ts
- packages/mock/src/util/root-cert.ts
- packages/mock/src/util/signing-cert.test.ts
- packages/mock/src/util/signing-cert.ts
Updates to the `@sigstore/mock` package so that the mock TSA instance can issue verifiable timestamps. 
The timestamps which were generated by the mock TSA previously were missing some critical fields which made them unverifiable. The signed timestamp now includes the necessary information about the certificate which was used to do the signing. This is used in the verification process to look-up the correct cert.
This change also introduces a new intermediate certificate with the "Time Stamping" key usage extension which is necessary for generating a valid timestamp (the verification process checks that the issuing certificate has this usage listed).
With these changes I was able to use `openssl ts -verify` to successfully verify a timestamp generated by the mock TSA instance.
> Fixes for TSA-generated timestamps in mock package

- .changeset/rude-meals-tap.md
- packages/mock/src/timestamp/tsa.ts
Minor change to the structure of the RFC3161 timestamps generated by the mock TSA to remove an unnecessary level of OCTET STRING encoding. The resulting timestamp looks more like ones which are generated by the real TSA service.
Before
After
> tweak encoded structure of mock tsa timestamps

- .changeset/healthy-walls-raise.md
- packages/core/src/__tests__/index.test.ts
- packages/core/src/__tests__/rfc3161/timestamp.test.ts
- packages/core/src/__tests__/rfc3161/tstinfo.test.ts
- packages/core/src/__tests__/x509/cert.test.ts
- packages/core/src/crypto.ts
- packages/core/src/oid.ts
- packages/core/src/rfc3161/error.ts
- packages/core/src/rfc3161/index.ts
- packages/core/src/rfc3161/timestamp.ts
- packages/core/src/rfc3161/tstinfo.ts
- packages/core/src/x509/cert.ts
Adds an `RFC3161Timestamp` class to the `@sigstore/core` package. This sets the stage for adding full signed timestamp verification to the `@sigstore/verify` package.
> support for parsing RFC3161 timestamps

- .changeset/neat-gorillas-eat.md
- packages/mock-server/src/index.ts
- packages/verify/src/__tests__/timestamp/tsa.test.ts
- packages/verify/src/__tests__/verifier.test.ts
- packages/verify/src/key/certificate.ts
- packages/verify/src/timestamp/index.ts
- packages/verify/src/timestamp/tsa.ts
- packages/verify/src/verifier.ts
Updates the `Verifier` in `@sigstore/verify` to perform full verification of any RFC3161 timestamps present in the Sigstore bundle against the trusted root.
> verify RFC3161 timestamps

- .changeset/new-birds-hide.md
- package-lock.json
- packages/tuf/README.md
- packages/tuf/package.json
- packages/tuf/src/__tests__/client.test.ts
- packages/tuf/src/client.ts
- packages/tuf/src/index.ts
Updates the `@sigstore/tuf` package with the `forceCache` option which was [added](https://github.com/theupdateframework/tuf-js/pull/575) to `tuf-js`.
To help disambiguate things, the `force` option was renamed to `forceInit`. The `forceInit` flag is the opposite of `forceCache` in that it will force a complete reset of the local TUF cache regardless of its current state. `forceInit` takes precedence over `forceCache`.
We will continue to support the old `force` flag for some time, but the preferred named is now `forceInit`.
> expose forceCache option in tuf package

- .changeset/long-jobs-explain.md
- .changeset/polite-numbers-wait.md
- .changeset/poor-radios-sleep.md
- packages/cli/README.md
- packages/cli/src/commands/initialize.ts
- packages/cli/src/commands/verify.ts
- packages/client/src/config.ts
- packages/client/src/sigstore.ts
A couple of `client` and `cli` updates related to the new `forceCache` option added to the `@sigstore/tuf` client:
* Updates the `verify` function in the client with a new `tufForceCache` option.
* Updates the `verify` command in the CLI with a new `--tuf-force-cache` flag.
* Updates the `initialize` command in the CLI with a new `--cache-path` flag.
> add tufForceCache to client and CLI

- .changeset/shaggy-rats-decide.md
- packages/verify/src/__tests__/timestamp/checkpoint.test.ts
- packages/verify/src/timestamp/checkpoint.ts
Updates tlog verification logic to properly handle checkpoint values which do NOT include timestamps. This data was never being used, but the verifier would throw an error if it was missing.
related: https://github.com/sigstore/rekor/pull/1888
> handle rekor checkpoints w/o timestamps

- .changeset/forty-jars-sparkle.md
- .changeset/hungry-teachers-mix.md
Promotes the `@sigstore/core` and `@sigstore/verify` packages to official 1.0.0 status
> promote new packages to v1.0.0

- .changeset/chilly-pugs-grow.md
- .changeset/chilly-swans-applaud.md
- .changeset/seven-countries-ring.md
- package-lock.json
- packages/bundle/package.json
- packages/bundle/src/__tests__/__snapshots__/serialized.test.ts.snap
- packages/bundle/src/__tests__/index.test.ts
- packages/bundle/src/__tests__/serialized.test.ts
- packages/bundle/src/__tests__/validate.test.ts
- packages/bundle/src/bundle.ts
- packages/bundle/src/index.ts
- packages/bundle/src/serialized.ts
- packages/bundle/src/validate.ts
- packages/client/package.json
- packages/client/src/__tests__/__fixtures__/bundles/valid.ts
- packages/client/src/__tests__/sigstore.test.ts
- packages/conformance/package.json
- packages/conformance/src/commands/verify.ts
- packages/mock/package.json
- packages/sign/package.json
- packages/tuf/package.json
- packages/verify/package.json
- packages/verify/src/__tests__/__fixtures__/bundles.ts
- packages/verify/src/__tests__/bundle/index.test.ts
- packages/verify/src/__tests__/verifier.test.ts
- packages/verify/src/bundle/index.ts
Add support for the new v0.3 bundle version (see https://github.com/sigstore/protobuf-specs/pull/213).
This change will ensure that we can verify v0.3 bundles, but does not yet generate v0.3 bundles.
> update to @sigstore/protobuf-specs@0.3.0

- .changeset/lovely-waves-hug.md
- packages/tuf/src/client.ts
Closes #989 
This pull request includes changes to how the TUF seeds are loaded in the `packages/tuf/src/client.ts` file. The most important change is the switch from using `require.resolve` to using `require` to load the seeds.
> load TUF seeds via require not require.resolve

- .changeset/large-beds-brush.md
- packages/oci/src/image.ts
Recent re-testing against the Docker Hub registry shows that it now supports OCI 1.1 compliant artifact management.
This change removes Docker Hub from the list of registries that would trigger a downgrade of the artifact manifest published when uploading an attestation bundle.
> remove docker hub from oci artifact downgrade list

- .changeset/clean-chefs-impress.md
- packages/oci/src/image.ts
Updates the AWS ECR specific code for pushing artifacts into the registry. Previously, we had to dumb-down the artifact manifest when pushing to ECR due to compatibility issues with this registry. It seems that some of the previous issues have been resolved and we can add back fields like `subject` and `artifactType` to the manifest.
The issue of ECR not accepting content types which contain a `;` character remains so we still need to do some transformation of the Sigstore bundle type before uploading the manifest to ECR.
> include subject/artifactType in ECR manifest

- .changeset/wet-spoons-end.md
- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/__tests__/oci/name.test.ts
- packages/cli/src/commands/attach.ts
- packages/cli/src/oci/name.ts
- packages/cli/tsconfig.json
Adds a new `attach` command to the CLI which can be used to push a Sigstore attestation bundle to an OCI registry and associated it with a container image.
> add new attach command to cli

- .changeset/silent-bugs-explain.md
- .changeset/three-rats-sleep.md
- packages/core/src/crypto.ts
- packages/verify/src/__tests__/__fixtures__/trust.ts
- packages/verify/src/__tests__/trust/index.test.ts
- packages/verify/src/trust/index.ts
Fixes a bug in `@sigstore/verify` which causes an error if the `trusted_root.json` file contains an RSA key using the "pkcs1" encoding.
> handle RSA keys in trusted_root.json

- .changeset/cyan-chairs-mate.md
- packages/bundle/src/__tests__/validate.test.ts
- packages/bundle/src/validate.ts
Fixes a bug in the regular expression used to detect valid media types for sigstore bundles.
This bug impacts only media type values using the new format introduced with the v0.3 bundle type.
> fix bug in mediatype regex

- .changeset/thick-buttons-tell.md
- .changeset/warm-snakes-fetch.md
- package-lock.json
- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/commands/attest.ts
- packages/cli/tsconfig.json
Updates `@sigstore/cli` with support for generating and verify v0.3 Sigstore bundles.
Note that the `attest` command is no longer using the main `sigstore` client to do signing, instead opting to use the `@sigstore/sign` library directly. This change allows us to force the creation of v0.3 bundles (the default in the `sigstore` library is still to output v0.2 bundles to maintain compat with npm).
> cli support for v0.3 bundles

- .changeset/tender-starfishes-turn.md
- package-lock.json
- packages/oci/package.json
- packages/oci/src/__tests__/fetch.test.ts
- packages/oci/src/__tests__/registry.test.ts
- packages/oci/src/error.ts
- packages/oci/src/fetch.ts
- packages/oci/src/image.ts
- packages/oci/src/index.ts
- packages/oci/src/proc-log.d.ts
- packages/oci/src/registry.ts
To compensate for the fact that `make-fetch-happen` doesn't support retries for "POST" requests, this change introduces a wrapper around the fetcher which will retry requests to Fulcio/Rekor/TSA for network errors or for HTTP status codes of 408, 429, or 5xx.
This is similar to #1148 but implemented specifically for the `@sigstore/oci` package.
> fix retry bug when calling oci apis

- .changeset/happy-beans-run.md
- packages/oci/src/image.ts
Fix a missing `await` in `OCIImage.addArtifact` which may cause the function to return before the referrers manifest has been uploaded.
> fix missing await in addArtifact

- .changeset/chilled-frogs-sort.md
- packages/oci/src/__tests__/image.test.ts
- packages/oci/src/__tests__/index.test.ts
- packages/oci/src/image.ts
- packages/oci/src/registry.ts
Updates the `attachArtifactToImage` function in the `@sigstore/oci` package to better detect registries which support the OCI referrers API.
Previously we were depending on the presence of the [`OCI-Subject`](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pushing-manifests-with-subject) header in response to uploading the artifact manifest to determine if the registry supported the referrers API. This was not a reliable method as some registries (AWS ECR) will return this header even when they do NOT support the referrers API.
As a fix, we're now pinging the referrers API directly to see if we get a 200 response. If we do, we can be confident that the registry supports the referrers API.
> Detect registries with referrers API support

- .changeset/lovely-numbers-run.md
- packages/oci/src/image.ts
Updates the logic used to detect whether an OCI registry supports the referrers API. It appears that some registries will return a false 200 response when hitting the `/referrers` endpoint even though the referrers API is not supported.
To ensure that we are correctly detecting support for the referrers API, this PR updates the logic to check for the presence of the `subjectDigest` in the artifact descriptor before checking the response from the `/referrers` endpoint.
> bug fix for referrers api detection

- .changeset/four-suits-sleep.md
- packages/bundle/src/__tests__/__snapshots__/build.test.ts.snap
- packages/bundle/src/__tests__/build.test.ts
- packages/bundle/src/build.ts
- packages/sign/src/bundler/bundle.ts
Update the `toDSSEBundle` and `toMessageSignatureBundle` functions in the `bundle` package to generate Sigstore v0.3 bundles by default.
Previously, these functions would generate v0.2 bundles by default and you could force v0.3 by setting `singleCertificate: true`. Now we will default to v0.3 and you can force v0.2 by setting `certificateChain` to true.
This is a breaking change to the public interface and will result in a major version bump.
> default to generating v0.3 bundles

- .changeset/cold-icons-dream.md
- packages/cli/src/commands/attest.ts
- packages/client/src/config.ts
- packages/sign/src/__tests__/bundler/bundle.test.ts
- packages/sign/src/__tests__/bundler/dsse.test.ts
- packages/sign/src/__tests__/integration.test.ts
- packages/sign/src/bundler/bundle.ts
- packages/sign/src/bundler/dsse.ts
Update the `DSSEBundleBuilder` class in the `sign` package to generate Sigstore v0.3 bundles by default.
Previously, this class would generate v0.2 bundles by default and you could force v0.3 by setting `singleCertificate: true`. Now we will default to v0.3 and you can force v0.2 by setting `certificateChain` to true.
This is a breaking change to the public interface and will result in a major version bump.
> default to signing v0.3 bundles

- .changeset/large-zoos-buy.md
- packages/core/src/__tests__/crypto.test.ts
- packages/core/src/crypto.ts
- packages/sign/src/__tests__/bundler/base.test.ts
- packages/sign/src/__tests__/bundler/bundle.test.ts
- packages/sign/src/__tests__/bundler/message.test.ts
- packages/sign/src/__tests__/witness/tlog/entry.test.ts
- packages/sign/src/__tests__/witness/tsa/client.test.ts
- packages/sign/src/bundler/bundle.ts
- packages/sign/src/witness/tlog/entry.ts
- packages/sign/src/witness/tsa/client.ts
- packages/verify/src/__tests__/bundle/dsse.test.ts
- packages/verify/src/__tests__/bundle/message.test.ts
- packages/verify/src/__tests__/key/index.test.ts
- packages/verify/src/__tests__/timestamp/checkpoint.test.ts
- packages/verify/src/__tests__/timestamp/index.test.ts
- packages/verify/src/__tests__/timestamp/merkle.test.ts
- packages/verify/src/__tests__/timestamp/set.test.ts
- packages/verify/src/bundle/dsse.ts
- packages/verify/src/key/sct.ts
- packages/verify/src/timestamp/merkle.ts
Remove the `hash` function in the `core` package. Change all uses of `hash` to the new `digest` function.
> remove `hash` function in core package

- .changeset/wet-waves-chew.md
- package-lock.json
- packages/mock/package.json
Drops support for node 16 in the `mock` package.
This is a breaking change.
> drop support for node 16 in mock package

- .changeset/tame-clouds-sparkle.md
- packages/client/src/config.ts
- packages/sign/src/__tests__/integration.test.ts
- packages/sign/src/__tests__/witness/tlog/entry.test.ts
- packages/sign/src/witness/tlog/entry.ts
Updates `RekorWitness` so that it generates "dsse" entries instead of "intoto" entries by default. The user can still request an "intoto" entry by explicitly setting the `entryType` field.
This is a breaking API change and will result in a major version bump.
> default to generating dsse rekor entries

- .changeset/cold-feet-roll.md
- .changeset/nasty-eyes-pretend.md
- package-lock.json
- packages/tuf/package.json
Updates to the `tuf` package:
* Drops support for node 16
* Bumps the `tuf-js` library from 2.2.1 to 3.0.0
> bump tuf-js from 2.2.1 to 3.0.0

- .changeset/beige-laws-deliver.md
- .changeset/big-spoons-fry.md
- .changeset/fast-eyes-jump.md
- package-lock.json
- packages/sign/package.json
Updates to the `sign` package:
* Drop support for node 16
* Bump `make-fetch-happen` from 13.0.1 to 14.0.1
* Bump `proc-log` from 4.2.0 to 5.0.0
> drop node 16 support in sign package

- .changeset/unlucky-baboons-suffer.md
- package-lock.json
- packages/rekor-types/package.json
Drop node 16 support in the `rekor-types` package.
> drop node 16 support in rekor-types package

- .changeset/hungry-mice-appear.md
- packages/rekor-types/hack/generate-rekor-types
- packages/rekor-types/src/__generated__/dsse.ts
- packages/rekor-types/src/__generated__/hashedrekord.ts
- packages/rekor-types/src/__generated__/index.ts
- packages/rekor-types/src/__generated__/models/ConsistencyProof.ts
- packages/rekor-types/src/__generated__/models/Error.ts
- packages/rekor-types/src/__generated__/models/InactiveShardLogInfo.ts
- packages/rekor-types/src/__generated__/models/InclusionProof.ts
- packages/rekor-types/src/__generated__/models/LogEntry.ts
- packages/rekor-types/src/__generated__/models/LogInfo.ts
- packages/rekor-types/src/__generated__/models/ProposedEntry.ts
- packages/rekor-types/src/__generated__/models/SearchIndex.ts
- packages/rekor-types/src/__generated__/models/SearchLogQuery.ts
- packages/rekor-types/src/__generated__/models/alpine.ts
- packages/rekor-types/src/__generated__/models/cose.ts
- packages/rekor-types/src/__generated__/models/dsse.ts
- packages/rekor-types/src/__generated__/models/hashedrekord.ts
- packages/rekor-types/src/__generated__/models/helm.ts
- packages/rekor-types/src/__generated__/models/intoto.ts
- packages/rekor-types/src/__generated__/models/jar.ts
- packages/rekor-types/src/__generated__/models/rekord.ts
- packages/rekor-types/src/__generated__/models/rfc3161.ts
- packages/rekor-types/src/__generated__/models/rpm.ts
- packages/rekor-types/src/__generated__/models/tuf.ts
Regenerate the rekor types from the `sigstore/rekor` repository version 1.3.6.
> regen rekor types from sigstore/rekor 1.3.6

- .changeset/sour-dolls-perform.md
- package-lock.json
- packages/client/package.json
Drop support for node 16 in the `client` package.
> drop node 16 support in client package

- .changeset/nasty-mangos-appear.md
- packages/client/README.md
- packages/client/src/__tests__/sigstore.test.ts
- packages/client/src/config.ts
Updates the `sign` and `attest` functions to generate bundles using the v0.3 format by default. Also changes the default Rekor log entry type from "intoto" to "dsse".
The previous behavior (v0.2 bundles and the "intoto" Rekor type) can be enabled with the new `legacyCompatibility` flag.
> add legacyCompatibility to sign/attest functions

- .changeset/thin-garlics-reflect.md
- packages/mock/src/rekor/tlog.test.ts
- packages/mock/src/rekor/tlog.ts
Fixes a bug in the mock Rekor server where the body of the log entry was not being encoded as a base64 string before being returned.
> Fix body encoding in mock Rekor server

- .changeset/tiny-comics-sleep.md
- packages/mock/src/fulcio/__snapshots__/handler.test.ts.snap
- packages/mock/src/fulcio/handler.test.ts
- packages/mock/src/fulcio/handler.ts
Updates the Fulcio mock service to support signing requests which include a PKCS#10 CSR (Certificate Signing Request) instead of raw public key (see [Fulcio API](https://github.com/sigstore/fulcio/blob/e585b021a1e489d5db61c7e9fdbc7b273e6f63db/fulcio.proto#L99-L109)).
> CSR support in Fulcio mock

- .changeset/tame-wasps-decide.md
- .github/workflows/conformance.yml
- package-lock.json
- packages/conformance/package.json
- packages/conformance/src/commands/verify-bundle.ts
Updates the CLI for the Sigstore conformance test suite to allow verification of bundles by artifact OR artifact digest.
The most recent release of the Sigstore conformance test suite ([v0.0.12](https://github.com/sigstore/sigstore-conformance/releases/tag/v0.0.12)) includes verification tests which supply only the digest of the signed artifact instead of supplying the artifact itself. The native nodejs crypto library does NOT support signature verification by digest (you must supply the original artifact and the digest is calculated internally). 
To work-around this, I've added a custom implementation of the `SignatureContent` type which uses a third-party library (`elliptic`) to perform the signature verification by digest. This new library is integrated ONLY with the conformance CLI …
> support verify by digest in conformance suite

- .changeset/late-hounds-kiss.md
- .github/workflows/conformance.yml
- package-lock.json
- packages/conformance/package.json
- packages/conformance/src/commands/verify-bundle.ts
- packages/conformance/src/commands/verify.ts
- packages/conformance/src/trust.ts
- packages/conformance/tsconfig.json
The `verify` command in the conformance suite driver was never fully implemented. This PR adds support for the `--trusted-root` flag and removes the `xfail` config for the tests we were previously skipping.
> Fix verify command in conformance CLI

- .github/workflows/conformance.yml
Bump `sigstore/sigstore-conformance` from 0.0.14 to 0.0.16.
https://github.com/sigstore/sigstore-conformance/releases/tag/v0.0.16
> bump sigstore conformance action to v0.0.16

- .changeset/odd-flowers-help.md
- packages/oci/src/__tests__/credentials.test.ts
- packages/oci/src/__tests__/image.test.ts
- packages/oci/src/__tests__/registry.test.ts
- packages/oci/src/credentials.ts
- packages/oci/src/registry.ts
Adds support for reading the `HttpHeaders` value from the Docker config file. These headers, if present, will be sent along with all requests to the OCI registry when attempting to attach an attestation to a container image.
> Support for `HttpHeaders` in Docker config
