CODEOWNERS

Updates the `CODEOWNERS` file w/ the `codeowners-sigstore-js` team

update codeowners w/ codeowners-sigstore-js team

---

src/identity/ci.test.ts
src/identity/ci.ts
src/identity/oauth.test.ts
src/identity/oauth.ts
src/sign.test.ts
src/sign.ts

This PR adds support for opening URLs in Linux and Windows.
Fixes #17

Fix oauth cross platform browser open

---

src/identity/oauth.test.ts

This PR fixes a failing test with Windows from #16. The tests did not run on the original PR but this has been fixed.
NONE

Fix oauth win test

---

.github/workflows/build-sign-verify.yml

Update workflow triggers to include `pull_request` so that PRs from forks will trigger workflow runs

update GHA workflow triggers

---

CODEOWNERS

Update codeowners to own everything in the repo so we get automatic PR review assignment.
NONE

Codeowners owns everything

---

README.md

Adding a few more items to the TODO list in the README (just to make it clear that we know we have lots of work to do still in the area of verification).

adding a few more items to TODO section of README

---

src/cli/index.ts
src/dsse.test.ts
src/encoding.test.ts
src/encoding.ts
src/identity/oauth.ts
src/sign.test.ts
src/sign.ts
src/util.test.ts
src/util.ts
src/verify.test.ts
src/verify.ts

Reorganization of some of the base64 encode/decode helpers into a dedicated module.
* Moves `base64Encode`/`base64Decode` helper functions out of "util" and into the new "encoding" module.
* Adds new base64-related helper functions for URL-safe operations:
* `base64URLEncode`
* `base64URLDecode`
* `base64URLEscape`
* `base64URLUnescape`

move base64 helpers into dedicated module

---

src/util.ts

Signed-off-by: eugene <ejahngithub@github.com>
small pr for adding node version in user agent

added node version in user agent

---

.github/workflows/build-sign-verify.yml
package-lock.json
package.json
src/index.ts
tsconfig.json

A few configuration clean-up items in preparation for publishing an alpha version of this package to the npmjs registry.
* Updates package version to `0.0.1-alpha.1`
* Fixes some bad URLs in the package.json
* Adds TypeScript types to build output

prep for publishing alpha package

---

src/util/index.ts
src/util/json.test.ts
src/util/json.ts

Adds a new `json.canonicalize` utility function. In order to perform verification of Rekor SET signatures we need to be able to serialize canonicalized JSON according to the rules [here](https://github.com/cyberphone/json-canonicalization).

JSON Canonicalization

---

.github/workflows/build-sign-verify.yml
package.json

Updating package version in preparation for publishing a new alpha release w/ the latest Sigstore bundle format changes.

bump package version to 0.0.2-alpha.2

---

.github/workflows/build-sign-verify.yml
package-lock.json
package.json

Bump version to `0.0.0-alpha.4`

update version to 0.0.1-alpha.4

---

README.md

I initially thought the project was limited to
signing npms so I looked elsewhere for something
that could sign any type of file. Reading further
on I realized from the instructions you could sign any type of file.
This PR improves the description to avoid that
confusion.
Signed-off-by: Michael Dawson <mdawson@devrus.com>
I initially thought the project was limited to
signing npms so I looked elsewhere for something
that could sign any type of file. Reading further
on I realized from the instructions you could sign
any type of file.
This PR improves the description to avoid that
confusion.
NONE
NO

doc: Improve description of intended use

---

tsconfig.json

Updates `tsconfig.json` to ensure that all tests/fixtures are excluded from build output.

ensure tests/fixtures excluded from build output

---

package-lock.json
package.json

Update package version to `0.1.0`

update version to 0.1.0

---

.github/workflows/publish.yml

Generate and publish an intoto build provenance statement for the `sigstore` package. At the moment, provenance generation is not publicly available and requires a pre-release version of the npm CLI as well as special configuration on the npm registry.

publish package w/ provenance

---

package-lock.json
package.json

bump version to v0.2.0

---

.github/workflows/publish.yml

This PR got automerged: https://github.com/sigstore/sigstore-js/pull/199

Publish with provenance

---

.github/workflows/auto-merge.yml

Fix bad formatting in "auto-merge.yml" workflow file

fix formatting in auto-merge.yml workflow

---

package-lock.json
package.json

Bumping package version for `v0.3.0` release.

bump package version to v0.3.0

---

package-lock.json
package.json

Updates the `jest` and `ts-jest` dev dependencies to the latest versions (and resolves https://github.com/sigstore/sigstore-js/security/dependabot/1).

update jest/ts-jest to latest versions

---

DEMO.md
README.md

Adds documentation for the public API interface to the README.
Moves the demo script into a separate markdown file.

update readme for 1.0 release

---

package-lock.json
package.json

Staging a new version so I can publish a release candidate for 1.0.0.

bump version to 1.0.0-beta.1

---

package-lock.json
package.json

Also includes `tuf-js` version 1.0.0.

Bump package version to 1.0.0

---

.github/workflows/scorecard.yml

Set-up [OSSF Scorecard](https://github.com/ossf/scorecard-action).
Closes https://github.com/sigstore/sigstore-js/issues/33

Add OSSF Scorecard Workflow

---

LICENSE

Add missing date and author in LICENSE file.

fix missing date/author in LICENSE

---

.changeset/gentle-foxes-visit.md
package-lock.json

Update to `tuf-js@1.1.2` (w/ `minimatch@7.4.2`). This will keep our `minimatch` version in sync w/ the version used by `npm` (https://github.com/npm/cli/pull/6275)

update tuf-js to v1.1.2

---

.changeset/kind-coins-crash.md
package-lock.json
packages/tuf/package.json

In the `@sigstore/tuf` pacakge, move the `@types/make-fetch-happen` dependency to a dev-only dependency.

fix @types/make-fetch-happen dependency in tuf pkg

---

.changeset/rude-turtles-care.md
package-lock.json
packages/tuf/package.json
packages/tuf/src/client.ts

Update `tuf-js` to version 2.0.0

update tuf-js to v2.0.0

---

.github/dependabot.yml

Adjust dependabot updates to a weekly schedule

change dependabot to weekly schedule

---

.changeset/four-mugs-approve.md
package-lock.json
packages/tuf/package.json

Bump the version of the `@tufjs/repo-mock` package in the `tuf` package.

bump @tufjs/repo-mock in tuf package

---

.changeset/hungry-items-appear.md
package-lock.json
packages/mock-server/package.json

Bump `@tufjs/repo-mock` in the `mock-server` package from 2.0.1 to 3.0.0

bump @tufjs/repo-mock in mock-server package
